apiVersion: v1
kind: Service
metadata:
  name: color-service-np
spec:
  type: NodePort
  selector:
    app: color
  ports:
    - name: http
      port: 8080        # Cluster IP http://10.109.199.234:port (docker exposed port)
      nodePort: 30085   # (EXTERNAL-IP VirtualBox IPs) http://192.168.50.11:nodePort/ http://192.168.50.12:nodePort/ http://192.168.50.13:nodePort/
      protocol: TCP        

# i.e. http://192.168.50.11:30085/